test tab detection

diff --git a/.github/workflows/shellcheck.yml b/.github/workflows/shellcheck.yml
--- a/.github/workflows/shellcheck.yml
+++ b/.github/workflows/shellcheck.yml
@@ -14,31 +14,37 @@ jobs:
       - uses: actions/checkout@v4
       - run: git fetch origin ${{ github.base_ref }}
 
-      - name: Download and set up shellcheck
+      - name: Download, setup, and run ShellCheck
+        shell: bash {0}
         run : |
           SC_URL="https://github.com/koalaman/shellcheck/releases/download/v0.10.0/shellcheck-v0.10.0.linux.x86_64.tar.xz"
           curl -fsSL "$SC_URL" | tar -Jx
           chmod +x "./shellcheck-v0.10.0/shellcheck"
 
-      - name: Run shellcheck
-        run: |
           error=0
-          for file in $(git diff --name-only origin/${{ github.base_ref }} HEAD core/tabs); do
+          files_to_check=$(git diff --name-only origin/${{ github.base_ref }} HEAD core/tabs)
+          for file in $files_to_check; do
               if [[ "$file" == *.sh ]] && [[ -f "$file" ]]; then
                   sc_output=$(./shellcheck-v0.10.0/shellcheck -fgcc -Serror "$file")
-                  parsed_errors=$(echo -e "$sc_output" | sed -n 's/\(.\+\)\:\([0-9]\+\)\:\([0-9]\+\)\: \(.*\)/::error file=\1,line=\2,col=\3::\4/p')
-                  iter_safe_errors=$(echo "$parsed_errors" | sed 's/ /:space:/g')
+                  iter_safe_parsed_errors=$(echo -e "$sc_output" | sed -n 's/\(.\+\)\:\([0-9]\+\)\:\([0-9]\+\)\: \(.*\)/::error file=\1,line=\2,col=\3::\4/p' | sed 's/ /:space:/g')
 
                   for error in $iter_safe_errors; do
                       echo "$error" | sed 's/:space:/ /g'
                       error=1
                   done
 
-                  tabs_detected=$(grep -nP '^\t+\w+' "$file")
-                  parsed_tabs_detected=$(echo "$tabs_detected" | sed -n 's,\([0-9]\+\).*,::error file='"$file"'\,line=\1::Found tab indentations,p')
-                  iter_safe_tabs_detected=$(echo "$parsed_tabs_detected" | sed 's/ /:space:/')
+                  tabs_detected=$(grep -nP '^\t+\S+' "$file")
 
-                  for error in $iter_safe_tabs_detected; do
+                  # fast fail on the action runner would fail immediately if there weren't any tabs found
+                  # this check makes sure that we don't continue if there's something really weird going on
+                  if [ "$?" = "2" ]; then
+                      echo "::error file=$file::There was a critical while grepping $file, aborting"
+                      exit 1
+                  fi
+
+                  iter_safe_parsed_tabs_detected=$(echo "$tabs_detected" | sed -n 's,\([0-9]\+\).*,::error file='"$file"'\,line=\1::Found tab indentations,p' | sed 's/ /:space:/g')
+
+                  for error in $iter_safe_parsed_tabs_detected; do
                       echo "$error" | sed 's/:space:/ /g'
                       error=1
                   done
